# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://karimali.ca # the base hostname & protocol for your site

# User settings
title: Karim Ali
email: karim.ali@nyu.edu
group: The SANAD Lab
groupweb: https://sanadlab.org/
dept: Computer Science
deptweb: https://nyuad.nyu.edu/en/academics/divisions/science/academic-programs/computer-science.html
institution: NYU Abu Dhabi
institutionweb: https://nyuad.nyu.edu/en/
address: A1-151
twitter: karimhamdanali
github: karimhamdanali
dblp: Ali_0001:Karim
gscholar: TC8495oAAAAJ

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 3
paginate_path: /news/page:num/
excerpt_separator: <!--more-->

# Site-wide variables
keywords: program analysis, compiler, static analysis, java, scala, call graphs, averroes
copyright: Copyright (c) Karim Ali

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
#  - jemoji
