# 2026
- name: ICSE
  role: Area Co‑Chair for Testing and Analysis
  year: 2026
  website: https://conf.researchr.org/home/icse-2026

# 2025
- name: PLDI
  role: PC Member
  year: 2025
  website: https://conf.researchr.org/home/pldi-2025

- name: SAS
  role: PC Member
  year: 2025
  website: https://2025.splashcon.org/home/sas-2025

# 2024
- name: CASCON
  role: PC Member
  year: 2024
  website: https://cascon.ca

- name: TSE
  role: Reviewer
  year: 2024
  website: https://www.computer.org/web/tse

- name: EMSE
  role: Reviewer
  year: 2024
  website: https://link.springer.com/journal/10664

# 2023
- name: OOPSLA
  role: PC Member
  year: 2023
  website: https://2023.splashcon.org

- name: ECOOP
  role: PC Co-Chair
  year: 2023
  website: https://2023.ecoop.org/

# 2022
- name: OOPSLA
  role: PC Member
  year: 2022
  website: https://2022.splashcon.org

- name: ECOOP
  role: PC Co-Chair
  year: 2022
  website: https://2022.ecoop.org/

- name: ICSE
  role: PC Member
  year: 2022
  website: https://conf.researchr.org/home/icse-2022

# 2021
- name: OOPSLA
  role: PC Member
  year: 2021
  website: https://2021.splashcon.org

- name: ICSE NIER
  role: PC Member
  year: 2021
  website: https://conf.researchr.org/home/icse-2021

# 2020
- name: OOPSLA
  role: PC Member
  year: 2020
  website: https://2020.splashcon.org

- name: ECOOP
  role: PC Member
  year: 2020
  website: https://2020.ecoop.org

- name: PLMW @ SPLASH
  role: Co-Organizer
  year: 2020
  website: https://2020.splashcon.org/home

- name: MSR Mining Challenge
  role: PC Member
  year: 2020
  website: https://2020.msrconf.org/track/msr-2020-mining-challenge

# 2019
- name: TOPLAS
  role: Reviewer
  year: 2019
  website: https://toplas.acm.org

- name: AORTA
  role: PC Member
  year: 2019
  website: https://2019.ecoop.org/home/aorta-2019

- name: SOAP
  role: PC Member
  year: 2019
  website: https://pldi19.sigplan.org/home/SOAP-2019

- name: PLMW @ SPLASH
  role: Co-Organizer
  year: 2019
  website: https://2019.splashcon.org/home

- name: TSE
  role: Reviewer
  year: 2019
  website: https://www.computer.org/web/tse

- name: ISSTA
  role: PC Member
  year: 2019
  website: https://conf.researchr.org/home/issta-2019

- name: SEAD @ ASE
  role: PC Member
  year: 2019
  website: https://2019.ase-conferences.org/home/sead-2019

# 2018
- name: SPLASH-I
  role: Co-Chair
  year: 2018
  website: https://2018.splashcon.org/home

- name: TOPLAS
  role: Reviewer
  year: 2018
  website: https://toplas.acm.org

- name: Program Analysis Hackathon (Panathon)
  role: Co-Organizer
  year: 2018
  website: https://conf.researchr.org/track/ecoop-issta-2018/panathon-2018

- name: Benchmarking Workshop (BenchWork)
  role: Co-Organizer
  year: 2018
  website: https://conf.researchr.org/track/ecoop-issta-2018/benchwork-2018-talks

- name: ECOOP
  role: PC Member
  year: 2018
  website: https://2018.ecoop.org

- name: ISSTA
  role: PC Member
  year: 2018
  website: https://conf.researchr.org/home/issta-2018

- name: ECOOP
  role: Web-Chair
  year: 2018
  website: https://2018.ecoop.org

- name: ISSTA
  role: Web-Chair
  year: 2018
  website: https://conf.researchr.org/home/issta-2018

# 2017
- name: SPLASH-I
  role: Co-Chair
  year: 2017
  website: https://2017.splashcon.org/home

- name: CDP @ CASCON
  role: Co-Organizer
  year: 2017
  website: https://cdp-cascon.github.io

- name: FSE
  role: Tool-Demo Co-Chair
  year: 2017
  website: http://esec-fse17.uni-paderborn.de

- name: CASCON
  role: PC Member
  year: 2017
  website: http://cascon.ca

- name: Onward!
  role: PC Member
  year: 2017
  website: https://2017.onward-conference.org/home

- name: WALA Hackathon @ PLDI
  role: Co-Organizer
  year: 2017
  website: https://pldi17.sigplan.org/event/pldi-2017-workshops-and-tutorials-wala-hack-a-thon

- name: SOAP @ PLDI
  role: PC Co-Chair
  year: 2017
  website: https://pldi17.sigplan.org/track/SOAP-2017-papers

- name: ESSoS
  role: Artifact Evaluation PC Co-Chair
  year: 2017
  website: https://distrinet.cs.kuleuven.be/events/essos/2017/

- name: CC
  role: Subreviewer
  year: 2017
  website: https://conf.researchr.org/home/CC-2017

# 2016
- name: ISSTA
  role: Artifact Evaluation PC Member
  year: 2016
  website: http://issta2016.cispa.saarland/index.html

- name: DECAF @ ISSTA
  role: Co-Organizer
  year: 2016
  website: https://karimali.ca/decaf

# 2015
- name: PLDI
  role: Artifact Evaluation PC Member
  year: 2015
  website: https://conf.researchr.org/home/pldi2015

- name: Workshop on WALA
  role: Co-Organizer
  year: 2015
  website: http://researcher.watson.ibm.com/researcher/view_group.php?id=5750

- name: ECOOP
  role: Artifact Evaluation PC Member
  year: 2015
  website: https://2015.ecoop.org/home

- name: SCP
  role: Reviewer
  year: 2015
  website: https://www.journals.elsevier.com/science-of-computer-programming/

# 2014
- name: ECOOP
  role: Artifact Evaluation PC Member
  year: 2014
  website: http://ecoop14.it.uu.se

# 2013
- name: TSE
  role: Reviewer
  year: 2013
  website: https://www.computer.org/web/tse
